// Code generated by "stringer -type=AstNodeKind -trimprefix=AstNode"; DO NOT EDIT.

package dgo

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AstNodeUndefined-0]
	_ = x[AstNodeRoot-1]
	_ = x[AstNodeDef-2]
	_ = x[AstNodeMsg-3]
	_ = x[AstNodeRsp-4]
	_ = x[AstNodeLoop-5]
	_ = x[AstNodeAlt-6]
	_ = x[AstNodeElse-7]
	_ = x[AstNodeEnd-8]
}

const _AstNodeKind_name = "UndefinedRootDefMsgRspLoopAltElseEnd"

var _AstNodeKind_index = [...]uint8{0, 9, 13, 16, 19, 22, 26, 29, 33, 36}

func (i AstNodeKind) String() string {
	if i >= AstNodeKind(len(_AstNodeKind_index)-1) {
		return "AstNodeKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _AstNodeKind_name[_AstNodeKind_index[i]:_AstNodeKind_index[i+1]]
}
