// Code generated by "stringer -type=AstNodeKind -trimprefix=AstNode"; DO NOT EDIT.

package dgo

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AstNodeUndefined-0]
	_ = x[AstNodeDef-1]
	_ = x[AstNodeMsg-2]
	_ = x[AstNodeRsp-3]
	_ = x[AstNodeLoop-4]
	_ = x[AstNodeAlt-5]
	_ = x[AstNodeElse-6]
	_ = x[AstNodeEnd-7]
}

const _AstNodeKind_name = "UndefinedDefMsgRspLoopAltElseEnd"

var _AstNodeKind_index = [...]uint8{0, 9, 12, 15, 18, 22, 25, 29, 32}

func (i AstNodeKind) String() string {
	if i >= AstNodeKind(len(_AstNodeKind_index)-1) {
		return "AstNodeKind(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _AstNodeKind_name[_AstNodeKind_index[i]:_AstNodeKind_index[i+1]]
}
